version: '3'
services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: xxx
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
